---
title: "MainCode"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(gganimate)
library(gifski)
library(png)
library(car)
library(leaps)
```
```
```
```
The purpose of the first part of our code is to clear the dataset and make it easier to read and easior to calculate.
```
```{r}
#Read Data
allData<-read.csv("WorldEconomicOutlookData.csv")
#Take a look at the data
summary(allData)
#All in char change into double
allData<-allData%>%mutate(WEO.Country.Code=as.integer(WEO.Country.Code),"1980"=as.integer(X1980),"1981"=as.integer(X1981),"1982"=as.integer(X1982),"1983"=as.integer(X1983),"1984"=as.integer(X1984),"1985"=as.integer(X1985),"1986"=as.integer(X1986),"1987"=as.integer(X1987),"1988"=as.integer(X1988),"1989"=as.integer(X1989),"1990"=as.integer(X1990),"1991"=as.integer(X1991),"1992"=as.integer(X1992),"1993"=as.integer(X1993),"1994"=as.integer(X1994),"1995"=as.integer(X1995),"1996"=as.integer(X1996),"1997"=as.integer(X1997),"1998"=as.integer(X1998),"1999"=as.integer(X1999),"2000"=as.integer(X2000),"2001"=as.integer(X2001),"2002"=as.integer(X2002),"2003"=as.integer(X2003),"2004"=as.integer(X2004),"2005"=as.integer(X2005),"2006"=as.integer(X2006),"2007"=as.integer(X2007),"2008"=as.integer(X2008),"2009"=as.integer(X2009),"2010"=as.integer(X2010),"2011"=as.integer(X2011),"2012"=as.integer(X2012),"2013"=as.integer(X2013),"2014"=as.integer(X2014),"2015"=as.integer(X2015),"2016"=as.integer(X2016),"2017"=as.integer(X2017),"2018"=as.integer(X2018),"2019"=as.integer(X2019),"2020"=as.integer(X2020),"2021"=as.integer(X2021),Estimates.Start.After=as.integer(Estimates.Start.After))
#See what the subject code means
discription<-unique(allData%>%select(WEO.Subject.Code,Subject.Descriptor,Units))
unique(discription)
#Change the subject code into something easier to understand
allData[allData$WEO.Subject.Code=="NGDP_RPCH","WEO.Subject.Code"]="NGDP(Percentage)"
allData[allData$WEO.Subject.Code=="PPPGDP","WEO.Subject.Code"]="RGDP (international dollars/Billions)"
allData[allData$WEO.Subject.Code=="NGDPRPPPPCPCH","WEO.Subject.Code"]="NGDP per person(Percentage)"
allData[allData$WEO.Subject.Code=="PCPIPCH","WEO.Subject.Code"]="Inflations rate average(Percentage)"
allData[allData$WEO.Subject.Code=="PCPIEPCH","WEO.Subject.Code"]="Inflations rate end(Percentage)"
allData[allData$WEO.Subject.Code=="LUR","WEO.Subject.Code"]="Unemployment rate(Percentage of Population)"
allData[allData$WEO.Subject.Code=="BCA_NGDPD","WEO.Subject.Code"]="Current account balance(Percentage of GDP)"
allData[allData$WEO.Subject.Code=="GGXCNL_NGDP","WEO.Subject.Code"]="Government net lending/borrowing(Percentage of GDP)"
#After making it easier to understand, get the data we want to us out
useData<-allData%>%select("Subject"=WEO.Subject.Code,Country,"1980":"2021",Estimates.Start.After)
#Drop the total NA rows
useData<-useData[-(1553:1554),]
#use pivot longer to reduce variables
useData<-useData%>%pivot_longer("1980":"2021",names_to = "Years",values_to="Value")
useData<-useData%>%mutate(Years=as.integer(Years))
#use pivot wider to dispose different subjects
useData<-useData%>%pivot_wider(names_from = Subject,values_from=Value)
```
```
```
```
Explain the choose of variables
Country.Code, ISO, and Country are the same thing. So, we just keep the country in our useData. Also, we composed most of the information of the subject.code(units, what is it...)into the new Variable "Subject" in the useData. So, we just left the numbers from 1980 to 2021 to further use it for data visualization and calculation.The Estimates.Start.After is the prediction made by the IMF, I left it here just for notification purpose.
```
```
```
```{r}
#Data visualization
#See the distribution of each subject of different countries from 1980 to 2021
#For NGDP
useData%>%ggplot(title="NGDP vs Years")+geom_line(aes(x=Years,y=`NGDP(Percentage)`,color=Country),na.rm = T)+ theme(legend.position = "none")+ggtitle("NGDP vs Years")
useData%>%ggplot(title="NGDP vs Years")+geom_line(aes(x=Years,y=`NGDP per person(Percentage)`,color=Country),na.rm = T)+ theme(legend.position = "none")+ggtitle("NGDP(per person) vs Years")
#The average NGDP percentage for people is quite consistent with the overall NGDP increase percentage.It seems that the NGDP is quite chaotic for each country. However, there is an apparent sharp decrease around 2010 and 2020. We would dig deeper into it later.
#For RGDP
useData%>%ggplot()+geom_line(aes(x=Years,y=`RGDP (international dollars/Billions)`,color=Country),na.rm = T)+ theme(legend.position = "none")+ggtitle("RGDP vs Years")
#Ha, the number in billions was continuesly increasing for RGDP.
useData%>%ggplot()+geom_line(aes(x=Years,y=`Inflations rate average(Percentage)`,color=Country),na.rm = T)+ theme(legend.position = "none")+ggtitle("Inflations rate vs Years")
useData%>%ggplot()+geom_line(aes(x=Years,y=`Inflations rate end(Percentage)`,color=Country),na.rm = T)+ theme(legend.position = "none")+ggtitle("Inflations rate vs Years")
#Seems wield that the inflation rate does not change much as the RGDP increased rapidly. Check on it.
#Unemployment rate
useData%>%ggplot()+geom_line(aes(x=Years,y=`Unemployment rate(Percentage of Population)`,color=Country),na.rm = T)+ theme(legend.position = "none")+ggtitle("Unemployment rate vs Years")
#Pretty chaos
#Government net lending/borrowing
useData%>%ggplot()+geom_line(aes(x=Years,y=`Government net lending/borrowing(Percentage of GDP)`,color=Country),na.rm = T)+ theme(legend.position = "none")+ggtitle("Government net lending/borrowing")
#Very consistent for each country.
#Current account balance
useData%>%ggplot()+geom_line(aes(x=Years,y=`Current account balance(Percentage of GDP)`,color=Country),na.rm = T)+ theme(legend.position = "none")+ggtitle("Current account balance")
#Pretty consistent between countries 
```
```
```
```{r}
#In this part,we would answer the question we have in the data visualization part.
#What had happened in 2009 and 2020 that the NGDP decreased for many of the countries?
#2009
useData[useData$Years==2009,]$`NGDP(Percentage)`
nrow(useData[useData$Years==2009&!is.na(useData$`NGDP(Percentage)`),])-nrow(useData[useData$Years==2009&useData$`NGDP(Percentage)`>0&!is.na(useData$`NGDP(Percentage)`),])
#105 out of 192 of the countries, of which we have data, have negative NGDP growth. Searched online, this is consequence of the 2008 would-wide financial crisis, which make sense.
#2020
useData[useData$Years==2020,]$`NGDP(Percentage)`
nrow(useData[useData$Years==2020&!is.na(useData$`NGDP(Percentage)`),])-nrow(useData[useData$Years==2020&useData$`NGDP(Percentage)`>0&!is.na(useData$`NGDP(Percentage)`),])
#161 out of 193 of the countries, of which we have data, have negative NGDP growth. COVID-19 is really making the economic down.
```
```
```
```{r}
#Lets calculate the data to see whether 2008 financial crisis is more serious or the COVID 19?
#See the NGDP first
#Firstly seperated by range
useDataCompare<-useData[useData$Years==2020|useData$Years==2009,]%>%select(Country,`NGDP(Percentage)`,Years)
useDataCompare<-useDataCompare%>%mutate(Range=" ")
useDataCompare[!is.na(useDataCompare$`NGDP(Percentage)`)&useDataCompare$`NGDP(Percentage)`>0,]$Range="positive"
useDataCompare[!is.na(useDataCompare$`NGDP(Percentage)`)&0>=useDataCompare$`NGDP(Percentage)`&useDataCompare$`NGDP(Percentage)`>-10,]$Range="-10 to 0"
useDataCompare[!is.na(useDataCompare$`NGDP(Percentage)`)&-10>=useDataCompare$`NGDP(Percentage)`&useDataCompare$`NGDP(Percentage)`>-20,]$Range="-20 to -10"
useDataCompare[!is.na(useDataCompare$`NGDP(Percentage)`)&-20>=useDataCompare$`NGDP(Percentage)`&useDataCompare$`NGDP(Percentage)`>-30,]$Range="-30 to -20"
useDataCompare[!is.na(useDataCompare$`NGDP(Percentage)`)&-30>=useDataCompare$`NGDP(Percentage)`&useDataCompare$`NGDP(Percentage)`>-40,]$Range="-40 to -30"
useDataCompare[!is.na(useDataCompare$`NGDP(Percentage)`)&-40>=useDataCompare$`NGDP(Percentage)`&useDataCompare$`NGDP(Percentage)`>-50,]$Range="-50 to -40"
useDataCompare[!is.na(useDataCompare$`NGDP(Percentage)`)&-50>=useDataCompare$`NGDP(Percentage)`,]$Range="smaller than -50"
#Get rid of NA values
useDataCompare<-useDataCompare[!is.na(useDataCompare$`NGDP(Percentage)`),]
#Seperate into 2009 and 2020
useDataCompare2009<-useDataCompare[useDataCompare$Years==2009,]
useDataCompare2020<-useDataCompare[useDataCompare$Years==2020,]
colors<- c("2020" = "light blue", "2009" = "pink")
ggplot(mapping=aes(x=Range))+geom_bar(data=useDataCompare2009,aes(fill="2009"))+geom_bar(data=useDataCompare2020,aes(fill="2020"))+ggtitle("2009 vs 2020 NGDP growth in percentage")+labs(x="Percentage of Growth in NGDP",y="Number of Countries",color="Years")+scale_fill_manual(values=colors)+theme(axis.text.x = element_text(angle = 90))
#As can be seen in the graph, 2009 has less negative growth NGDP, but more positive ones. 

#RGDP may be imprecise due to inflation. We would go ahead to see the unemployment rate
useDataUR<-useData[useData$Years==2020|useData$Years==2009,]%>%select(Country,`Unemployment rate(Percentage of Population)`,Years)
useDataUR<-useDataUR%>%mutate(Range=" ")
useDataUR[!is.na(useDataUR$`Unemployment rate(Percentage of Population)`)&useDataUR$`Unemployment rate(Percentage of Population)`>30,]$Range="Larger than 30"
useDataUR[!is.na(useDataUR$`Unemployment rate(Percentage of Population)`)&30>=useDataUR$`Unemployment rate(Percentage of Population)`&useDataUR$`Unemployment rate(Percentage of Population)`>20,]$Range="20 to 30"
useDataUR[!is.na(useDataUR$`Unemployment rate(Percentage of Population)`)&20>=useDataUR$`Unemployment rate(Percentage of Population)`&useDataUR$`Unemployment rate(Percentage of Population)`>10,]$Range="10 to 20"
useDataUR[!is.na(useDataUR$`Unemployment rate(Percentage of Population)`)&10>=useDataUR$`Unemployment rate(Percentage of Population)`&useDataUR$`Unemployment rate(Percentage of Population)`>=0,]$Range="0 to 10"
#Get rid of NA values
useDataUR<-useDataUR[!is.na(useDataUR$`Unemployment rate(Percentage of Population)`),]
#Seperate into 2009 and 2020
useDataUR2009<-useDataUR[useDataUR$Years==2009,]
useDataUR2020<-useDataUR[useDataUR$Years==2020,]
ggplot(mapping=aes(x=Range))+geom_bar(data=useDataUR2009,aes(fill="2009"))+geom_bar(data=useDataUR2020,aes(fill="2020"))+ggtitle("2009 vs 2020 Unemployer rate")+labs(x="Unemployer rate",y="Number of Countries",color="Years")+scale_fill_manual(values=colors)
#As can been seen from the graph, the unemployment rate is also a lot higher in 2020 than in 2009
#As RGDP does not show how economy is due to inflation and other variables are no direct relation to the good or worth an economy is.
#So, it can be concluded that 2020 COVID-19 has bigger influence to the economics than the 2009 financial crisis.
```
```
```
```{r}
#Doing regression
#First of all to make calculation easier, remove all the NA
useDataNoNA<-na.omit(useData)
#Rename to make the regression easier to read
useDataNoNA<-useDataNoNA%>%rename("NGDP"=`NGDP(Percentage)`,"RGDP"=`RGDP (international dollars/Billions)`,"IRA"=`Inflations rate average(Percentage)`,"IRE"=`Inflations rate end(Percentage)`,"UR"=`Unemployment rate(Percentage of Population)`,"GLB"=`Government net lending/borrowing(Percentage of GDP)`,"CAB"=`Current account balance(Percentage of GDP)`)
#For all, we want to know whether there is some relationship between NGDP growth percent and other things.
#Do the regression on whole and then conduct multicollinearity test to remove variables
reg<-lm(data = useDataNoNA,NGDP~Years+RGDP+IRA+IRE+UR+GLB+CAB)
summary(reg)
#Run multicollinearity test
vif(reg)
#It seems that Inflation rate average and Inflation rate end is highly related. We would choose Inflation rate average as it is a more precise description of the inflation rate of a year.
reg<-lm(data = useDataNoNA,NGDP~Years+RGDP+IRA+UR+GLB+CAB)
summary(reg)
#Doing backward model selection to get the best predict variables
mod_sel<-regsubsets(NGDP~Years+RGDP+IRA+UR+GLB+CAB,data=useDataNoNA,nbest = 1,nvmax = 6,method = "backward")
plot(mod_sel,scale = "adjr2")
#As can be seen in the graph, the government lending/borrowing is has the most influence on NGDP(the biggest adjusted R^2), the second is the inflation rate average. However, even add up all the variables, the adjusted R^2 is still as small as 0.1363, meaning only 13.63% of the data could be explained by the variables. So, overall, we can conclude that the NGDP growth percent has very weak relationship with the other variables.
```
```
```
```{r}
#If have time use outside dataset to better predict the NGDP. 
```
```
```
```{r}
#Graph and GIF for PPT
```

